package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Examples5'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Examples5")) {
    params {
        expect {
            param("env.CIRCLE_NODE_INDEX", "5")
        }
        update {
            param("env.CIRCLE_NODE_INDEX", "4")
        }
    }
}
