package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Examples'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Examples")) {
    check(name == "Examples") {
        "Unexpected name: '$name'"
    }
    name = "Aggregate"

    check(type == BuildTypeSettings.Type.COMPOSITE) {
        "Unexpected option value: type = $type"
    }
    type = BuildTypeSettings.Type.REGULAR

    expectSteps {
    }
    steps {
        insert(0) {
            script {
                scriptContent = "echo 'Done'"
            }
        }
    }
}
