package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.failureConditions.BuildFailureOnMetric
import jetbrains.buildServer.configs.kotlin.v2019_2.failureConditions.failOnMetricChange
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Lint'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Lint")) {
    failureConditions {
        add {
            failOnMetricChange {
                metric = BuildFailureOnMetric.MetricType.INSPECTION_ERROR_COUNT
                threshold = 0
                units = BuildFailureOnMetric.MetricUnit.DEFAULT_UNIT
                comparison = BuildFailureOnMetric.MetricComparison.MORE
                compareTo = value()
            }
        }
    }
}
