package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Test'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Test")) {
    expectSteps {
        script {
            scriptContent = """
                #!/bin/bash
                set -e -x
                
                yarn install
                
                # TODO remove after merging
                yarn add -DW --ignore-scripts jest-teamcity
                
                yarn jest --coverage -w 2 --testResultsProcessor=jest-teamcity
            """.trimIndent()
            dockerImage = "circleci/node:10"
            dockerImagePlatform = ScriptBuildStep.ImagePlatform.Linux
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            dockerImage = "node:10"
        }
    }
}
