package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    expectBuildTypesOrder()
    buildTypesOrderIds = arrayListOf(RelativeId("TestWorkflow"), RelativeId("Build"), RelativeId("Chromatic"), RelativeId("Coverage"), RelativeId("Docs"), RelativeId("E2E"), RelativeId("Examples"), RelativeId("Frontpage"), RelativeId("Lint"), RelativeId("Packtracker"), RelativeId("SmokeTests"), RelativeId("Test"))
}
