package patches.templates

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.Swabra
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.swabra
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the template with id = 'Common'
accordingly, and delete the patch script.
*/
changeTemplate(RelativeId("Common")) {
    features {
        val feature1 = find<Swabra> {
            swabra {
                id = "swabra"
                verbose = true
                paths = "-:**/node_modules/**"
            }
        }
        feature1.apply {
            paths = """
                -:*/node_modules
                -:node_modules
                -:*/node_modules/*
                -:node_modules/*
            """.trimIndent()
        }
    }
}
