name: CI

on:
  pull_request:
    paths-ignore: ["**.md"]
  push:
    branches: ["next"]
    paths-ignore: ["**.md"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14.x, 16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use node@${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
      - name: Install Chromium
        run: npx playwright install-deps chromium
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Run tests
        run: npm run ci:test
      - name: Report code coverage
        run: npm run ci:report
